name: "postprocessing"
backend: "python"
max_batch_size: 882352
input [
    {
        name: "CLASS_IDX"
        data_type: TYPE_FP32
        dims: [ 1 ]
        reshape: { shape: [ ] }
    }
]
output [
    {
        name: "CLASS_LABEL"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]
